/** Fragenkatalog für "Mehrheit gewinnt": [Option A, Option B]. Einfach Zeilen ergänzen. */
export const QUESTIONS: [string, string][] = [
  ["Berge ⛰️", "Meer 🌊"],
  ["Kaffee ☕", "Tee 🍵"],
  ["Hund 🐶", "Katze 🐱"],
  ["Sommer ☀️", "Winter ❄️"],
  ["Frühaufsteher 🌅", "Nachteule 🦉"],
  ["Pizza 🍕", "Pasta 🍝"],
  ["Süß 🍰", "Salzig 🥨"],
  ["Kino 🎬", "Netflix zu Hause 🛋️"],
  ["Buch 📚", "Film 🎥"],
  ["Stadturlaub 🏙️", "Campingurlaub ⛺"],
  ["Duschen 🚿", "Baden 🛁"],
  ["Schokolade 🍫", "Chips 🥔"],
  ["Auto 🚗", "Zug 🚆"],
  ["Fliegen ✈️", "Schiff 🚢"],
  ["Pünktlich sein ⏰", "Spontan sein 🎈"],
  ["Anrufen 📞", "Nachricht schreiben 💬"],
  ["Frühstück 🥐", "Abendessen 🍽️"],
  ["Eis im Becher 🍨", "Eis in der Waffel 🍦"],
  ["Sofa 🛋️", "Spaziergang 🚶"],
  ["Sonnenaufgang 🌄", "Sonnenuntergang 🌇"],
  ["Pommes mit Ketchup 🍟", "Pommes mit Mayo 🥫"],
  ["Gemeinsam kochen 👩‍🍳", "Essen gehen 🍴"],
  ["Brettspiele 🎲", "Videospiele 🎮"],
  ["Warm duschen 🔥", "Kalt duschen 🧊"],
  ["Land 🌾", "Stadt 🌆"],
  ["Haus mit Garten 🏡", "Wohnung mitten in der Stadt 🏢"],
  ["Lieber reden 🗣️", "Lieber zuhören 👂"],
  ["Sparen 🐷", "Ausgeben 🛍️"],
  ["Früher Feierabend 🏃", "Langes Ausschlafen 😴"],
  ["Unendlich Pizza 🍕", "Unendlich Eis 🍦"],
  ["Superkraft: Fliegen 🦸", "Superkraft: Unsichtbar sein 🫥"],
  ["In die Vergangenheit reisen ⏪", "In die Zukunft reisen ⏩"],
  ["Berühmt sein ⭐", "Reich sein 💰"],
  ["Nur noch Sommer 🏖️", "Nur noch Winter ⛄"],
  ["Nie mehr Hausarbeit 🧹", "Nie mehr Hunger 🍔"],
  ["Tiere sprechen können 🦜", "Jede Sprache sprechen 🌍"],
  ["Weihnachten 🎄", "Ostern 🐣"],
  ["Geburtstag groß feiern 🎉", "Geburtstag ruhig verbringen 🕯️"],
  ["Geschenke bekommen 🎁", "Geschenke machen 💝"],
  ["Lieber Geschenk auspacken 🎀", "Lieber Überraschungsausflug 🎟️"],
  ["Spaghetti schneiden ✂️", "Spaghetti aufdrehen 🌀"],
  ["Ananas auf Pizza 🍍", "Ananas niemals 🚫"],
  ["Vanille 🍦", "Schoko 🍫"],
  ["Apfel 🍎", "Banane 🍌"],
  ["Rot 🔴", "Blau 🔵"],
  ["Radfahren 🚴", "Schwimmen 🏊"],
  ["Wandern 🥾", "Shoppen 🛍️"],
  ["Konzert 🎤", "Theater 🎭"],
  ["Pizzaboden dünn 🫓", "Pizzaboden dick 🍞"],
  ["Lieber zu früh 🕰️", "Lieber zu spät 🐢"],
  ["Mit Wecker aufstehen ⏰", "Von allein aufwachen 🌤️"],
  ["Pyjama-Tag 🧸", "Ausflugs-Tag 🗺️"],
  ["Lieber Fernseher 📺", "Lieber Tablet 📱"],
  ["Podcasts 🎧", "Musik 🎶"],
  ["Mit Strand-Buch 🏖️📖", "Mit Strand-Spielen 🏐"],
  ["Skifahren ⛷️", "Schlittenfahren 🛷"],
  ["Käse 🧀", "Wurst 🌭"],
  ["Suppe 🥣", "Salat 🥗"],
  ["Morgens Sport 🏋️", "Abends Sport 🌙"],
  ["Schlosshotel 🏰", "Hütte im Wald 🛖"],
  ["Allein verreisen 🧳", "Mit der ganzen Familie verreisen 👨‍👩‍👧‍👧"],
  ["Zelt ⛺", "Wohnmobil 🚐"],
  ["Zoo 🦒", "Freizeitpark 🎢"],
];
